mod_id=storagemanager
mod_name=Storage Manager
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.duox.storagemanager
mod_authors=Duox
mod_description=Storage Manager
neo_version=21.11.37-beta
minecraft_version=1.21.11
minecraft_version_range=[1.21, 1.22)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.11
