mod_id=advancedutilities
mod_name=Advanced Utilities
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.duox.advancedutilities
mod_authors=Duox
mod_description=Advanced Utilities Mod
neo_version=21.1.1
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.1
